name: generate badge
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  update:
    name: Update stats card
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Ensures repo is checked out
        with:
          token: ${{ secrets.GH_PAT }}  # Use your token for checkout

      - uses: datarootsio/github-stats-card@v1
        with:
          username: R-Sourabh  # Replace with your actual GitHub username
          gh_token_stats: ${{ secrets.GH_PAT }}
          gh_token_commits: ${{ secrets.GH_PAT }}
          badge_path: assets/badge.svg
          header: "👋 Hi, I'm"
          about: "Code is like humor. When you have to explain it, it’s bad. \nPassionate about coding and open-source."
          theme: a-colibri-hums-while-the-dog-farts
          commit_message: "Badge updated automatically 🎉"
