name: generate badge
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  update:
    name: Update stats card
    runs-on: ubuntu-latest
    steps:
      - uses: datarootsio/github-stats-card@v1
        with:
          username: R-Sourabh
          gh_token_stats: ${{ secrets.GH_PAT }}
          gh_token_commits: ${{ secrets.GITHUB_TOKEN }}
          badge_path: assets/badge.svg
          header: "👋 Hi, I'm"
          about: "Code is like humor. When you have to explain it, it’s bad. \nPassionate about open-source & problem-solving!"
          theme: hypnotoad
          commit_message: "Badge updated automatically 🎉"
